version: "3.3"
services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ../app:/var/www/html
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5555:${DB_PORT}

  nginx:
    image: nginx:latest
    links:
      - php
    ports:
      - 8001:80
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx/
